
CREATE SEQUENCE GUEST_SEQ
    START WITH 1
    INCREMENT BY 1
   	nocache;

DROP SEQUENCE GUEST_SEQ;

--1 여자, 2남자


DELETE FROM guest WHERE guest_name IN ('김혜진','고연정','이나라','최순호','김연지','고연정2');
DELETE GUEST;
DELETE FROM guest WHERE guest_name ='sadasdasd';

INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, '고연정', TO_DATE('1990-02-20', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 1, NULL);
INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, '김연지', TO_DATE('1992-09-09', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 1, NULL);
INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, '이나라', TO_DATE('1987-06-01', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 2, NULL);
INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, '최순호', TO_DATE('1990-10-11', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 2, NULL);
INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, '고연정', TO_DATE('1990-02-20', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 1, NULL);
INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, '이지수', TO_DATE('1990-02-20', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 1, NULL);

--selectByAll
SELECT GUEST_NO, GUEST_NAME, BIRTHDAY, JOIN_DAY, PHONE, GENDER, GUEST_NOTE FROM GUEST ORDER BY GUEST_NO ;

--selectByName
SELECT  GUEST_NO, GUEST_NAME, BIRTHDAY, JOIN_DAY, PHONE, GENDER, GUEST_NOTE FROM GUEST WHERE GUEST_NAME = '고연정';

--selectByNo
SELECT GUEST_NO, GUEST_NAME, BIRTHDAY, JOIN_DAY, PHONE, GENDER, GUEST_NOTE FROM GUEST WHERE GUEST_NO = 6;

--insert 
INSERT INTO GUEST VALUES(GUEST_SEQ.NEXTVAL, ?,  TO_DATE(?, 'YYYY-MM-DD'), SYSDATE, ?, ?, ?);

--UPDATE 
UPDATE guest SET guest_name = '고연정', birthday ='1991-12-19' , phone = '010-0000-0000', gender = '2', guest_note = '변경' WHERE guest_no = 5;

--searchByName
SELECT GUEST_NO, GUEST_NAME, BIRTHDAY, JOIN_DAY, PHONE, GENDER, GUEST_NOTE FROM GUEST WHERE GUEST_NAME LIKE '%고연%';

--마지막시퀀스조회/다음번호
SELECT GUEST_SEQ.currval FROM DUAL;

SELECT * from USER_SEQUENCES
WHERE SEQUENCE_NAME = 'GUEST_SEQ';

SELECT * FROM guest;


