CREATE SEQUENCE GUEST_SEQ
    START WITH 1
    INCREMENT BY 1;

DROP SEQUENCE GUEST_SEQ;

INSERT INTO GUEST
VALUES(GUEST_SEQ.NEXTVAL, '이지수', TO_DATE('1900-01-02', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 2, NULL);
	
SELECT *
FROM GUEST;

SELECT *
	FROM 
DELETE GUEST;

INSERT INTO GUEST
VALUES(GUEST_SEQ.NEXTVAL, '김대훈', TO_DATE('1900-12-01', 'YYYY-MM-DD'), SYSDATE, '010-4321-8765', 1, NULL);

INSERT INTO HAIR VALUES (1,'커트',3000);

SELECT * FROM HAIR;

--GUEST완

CREATE SEQUENCE SALDETAIL_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE sales_seq
	START WITH 1
	INCREMENT BY 1;


--INSERT INTO SALES 
--value(sales_seq.nextval, to_date('2020-08-01', 'YYYY-MM-DD'), to_date('2020');



-- sales detail, sales 시퀀스 완




CREATE SEQUENCE EVENT_SEQ
	START WITH 1
	INCREMENT BY 1;
	
CREATE SEQUENCE BOOKING_SEQ
	START WITH 1
	INCREMENT BY 1;