CREATE TABLE Guest(
GUEST_NO	NUMBER(10) PRIMARY KEY,
GUEST_NAME	VARCHAR2(20) NOT NULL,
BIRTHDAY	DATE,
JOIN_DAY	DATE,
PHONE		VARCHAR2(13),
GENDER		NUMBER(1),
GUEST_NOTE	VARCHAR2(500)
);

CREATE TABLE SALES(
	SALES_NO	NUMBER(10) PRIMARY KEY,
	SALES_DAY	DATE,
	GUEST_NO	NUMBER(10),
	EVENT_NO	NUMBER(10),
	HAIR_NO 	NUMBER(10)
);



CREATE TABLE EVENT(
	EVENT_NO	NUMBER(10) PRIMARY KEY,
	EVENT_NAME	VARCHAR2(20) NOT NULL,
	SALE	NUMBER(3, 2) NOT NULL CONSTRAINT EVENT_SALE_CK CHECK (SALE BETWEEN 0 AND 1)
);

CREATE TABLE HAIR(
	HAIR_NO	NUMBER(10) PRIMARY KEY,
	HAIR_NAME	VARCHAR2(20) NOT NULL,
	PRICE	NUMBER	NOT NULL
);

CREATE TABLE BOOKING(
	BOOK_NO		NUMBER(10) PRIMARY KEY,
	GUEST_NO	NUMBER(10),
	BOOK_DAY	DATE,
	HAIR_NO		NUMBER(10),
	BOOK_NOTE	VARCHAR2(500)
);

SELECT * FROM SALES;
SELECT * FROM GUEST;
SELECT * FROM BOOKING;
SELECT * FROM EVENT ;
SELECT * FROM HAIR;

SELECT *
FROM USER_CONSTRAINTS;

ALTER TABLE SALES
ADD CONSTRAINT SALES_GUESTNO_FK FOREIGN KEY (GUEST_NO) REFERENCES GUEST(GUEST_NO);

ALTER TABLE SALES
ADD CONSTRAINT SALES_EVENTNO_FK FOREIGN KEY (EVENT_NO) REFERENCES EVENT(EVENT_NO);

ALTER TABLE SALES
ADD CONSTRAINT SALES_HAIRNO_FK FOREIGN KEY (HAIR_NO) REFERENCES HAIR(HAIR_NO);

ALTER TABLE BOOKING
ADD CONSTRAINT BOOK_GUESTNO_FK FOREIGN KEY (GUEST_NO) REFERENCES GUEST(GUEST_NO);

ALTER TABLE BOOKING
ADD CONSTRAINT BOOK_HAIRNO_FK FOREIGN KEY (HAIR_NO) REFERENCES HAIR(HAIR_NO);
